In [1]:
from hopfield import *

In [2]:
Hop = Hopfield(shape = (200,1))

In [3]:
Hop.train_on_values()

In [4]:
for train in range(60):
    new_img = np.random.choice([-1, 1], size = 200)
    Hop.storkey_train(new_img)

In [5]:
Hop.weights

array([[ 0.   , -0.005,  0.035, ...,  0.035, -0.045, -0.085],
       [-0.005,  0.   ,  0.045, ..., -0.015, -0.015,  0.025],
       [ 0.035,  0.045,  0.   , ...,  0.025, -0.035,  0.045],
       ...,
       [ 0.035, -0.015,  0.025, ...,  0.   , -0.015, -0.015],
       [-0.045, -0.015, -0.035, ..., -0.015,  0.   , -0.035],
       [-0.085,  0.025,  0.045, ..., -0.015, -0.035,  0.   ]])

In [6]:
Hop.perturb(num = 40)

In [7]:
Hop.energy_function()

-38.690000000000296

In [8]:
Hop.sync_update_until_steady()

[[-98.43999999999804,
  -111.35999999999598,
  -114.88999999999594,
  -115.48999999999613,
  -114.67999999999546,
  -115.56999999999607,
  -115.95999999999556,
  -115.91999999999615,
  -116.71999999999552,
  -118.15999999999606],
 10]

In [9]:
Hop = Hopfield(shape = (4,1))

In [10]:
Hop.weights

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
Hop.storkey_train(np.array([1,1,-1,1]))

In [131]:
Hop.weights

array([[ 0.25,  0.25, -0.25,  0.25],
       [ 0.25,  0.25, -0.25,  0.25],
       [-0.25, -0.25,  0.25, -0.25],
       [ 0.25,  0.25, -0.25,  0.25]])

In [132]:
Hop.storkey_train(np.array([1,-1,1,-1]))

In [133]:
Hop.weights

array([[ 0.875,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.375, -0.5  ,  0.5  ],
       [ 0.   , -0.5  ,  0.375, -0.5  ],
       [ 0.   ,  0.5  , -0.5  ,  0.375]])